export const KNOWLEDGE_PACK_VERSION = 1;

export function createKnowledgePack({
  subjectId,
  topicId,
  displayName = '',
  learningObjectives = [],
  explanations = [],
  teacherExplanation = [],
  simpleExplanation = '',
  workedExamples = [],
  examples = [],
  extraExamples = [],
  problemSolvingSteps = [],
  memoryTips = [],
  tips = [],
  commonMistakes = [],
  movementSteps = [],
  coordinationTips = [],
  fitnessActivities = [],
  warmUpIdeas = [],
  coolDownIdeas = [],
  safetyRules = [],
  equipmentUse = [],
  gameApplications = [],
  bodyAwareness = [],
  dailyMovementIdeas = [],
  healthyHabits = [],
  hygieneSteps = [],
  nutritionTips = [],
  personalSafety = [],
  emotionSkills = [],
  helpSeekingSteps = [],
  realLifeScenarios = [],
  bodyCare = [],
  familyHealthIdeas = [],
  scientificFacts = [],
  observationPrompts = [],
  comparisonPrompts = [],
  investigationIdeas = [],
  realLifeConnections = [],
  safetyNotes = [],
  misconceptions = [],
  evidenceQuestions = [],
  pronunciationTips = [],
  letterRecognitionTips = [],
  writingTips = [],
  vocabularyGroups = [],
  translationHints = [],
  readingPractice = [],
  listeningPractice = [],
  speakingPractice = [],
  writingPractice = [],
  commonPronunciationMistakes = [],
  dailyPractice = [],
  adabApplications = [],
  realLifeExamples = [],
  ayahOrHadithReference = [],
  reflectionQuestions = [],
  goodDeedsIdeas = [],
  relatedTopics = [],
  difficulty = 'easy',
  curriculum = {},
  keywords = [],
  questionPatterns = [],
  wrongAnswerPatterns = [],
  followUpQuestions = [],
  encouragement = {}
} = {}) {
  return {
    version: KNOWLEDGE_PACK_VERSION,
    subjectId,
    topicId,
    displayName,
    learningObjectives: Array.isArray(learningObjectives) ? learningObjectives : [],
    explanations: Array.isArray(explanations) ? explanations : [],
    teacherExplanation: Array.isArray(teacherExplanation) ? teacherExplanation : [],
    simpleExplanation: String(simpleExplanation || ''),
    workedExamples: Array.isArray(workedExamples) ? workedExamples : [],
    examples: Array.isArray(examples) ? examples : [],
    extraExamples: Array.isArray(extraExamples) ? extraExamples : [],
    problemSolvingSteps: Array.isArray(problemSolvingSteps) ? problemSolvingSteps : [],
    memoryTips: Array.isArray(memoryTips) ? memoryTips : [],
    tips: Array.isArray(tips) ? tips : [],
    commonMistakes: Array.isArray(commonMistakes) ? commonMistakes : [],
    movementSteps: Array.isArray(movementSteps) ? movementSteps : [],
    coordinationTips: Array.isArray(coordinationTips) ? coordinationTips : [],
    fitnessActivities: Array.isArray(fitnessActivities) ? fitnessActivities : [],
    warmUpIdeas: Array.isArray(warmUpIdeas) ? warmUpIdeas : [],
    coolDownIdeas: Array.isArray(coolDownIdeas) ? coolDownIdeas : [],
    safetyRules: Array.isArray(safetyRules) ? safetyRules : [],
    equipmentUse: Array.isArray(equipmentUse) ? equipmentUse : [],
    gameApplications: Array.isArray(gameApplications) ? gameApplications : [],
    bodyAwareness: Array.isArray(bodyAwareness) ? bodyAwareness : [],
    dailyMovementIdeas: Array.isArray(dailyMovementIdeas) ? dailyMovementIdeas : [],
    healthyHabits: Array.isArray(healthyHabits) ? healthyHabits : [],
    hygieneSteps: Array.isArray(hygieneSteps) ? hygieneSteps : [],
    nutritionTips: Array.isArray(nutritionTips) ? nutritionTips : [],
    personalSafety: Array.isArray(personalSafety) ? personalSafety : [],
    emotionSkills: Array.isArray(emotionSkills) ? emotionSkills : [],
    helpSeekingSteps: Array.isArray(helpSeekingSteps) ? helpSeekingSteps : [],
    realLifeScenarios: Array.isArray(realLifeScenarios) ? realLifeScenarios : [],
    bodyCare: Array.isArray(bodyCare) ? bodyCare : [],
    familyHealthIdeas: Array.isArray(familyHealthIdeas) ? familyHealthIdeas : [],
    scientificFacts: Array.isArray(scientificFacts) ? scientificFacts : [],
    observationPrompts: Array.isArray(observationPrompts) ? observationPrompts : [],
    comparisonPrompts: Array.isArray(comparisonPrompts) ? comparisonPrompts : [],
    investigationIdeas: Array.isArray(investigationIdeas) ? investigationIdeas : [],
    realLifeConnections: Array.isArray(realLifeConnections) ? realLifeConnections : [],
    safetyNotes: Array.isArray(safetyNotes) ? safetyNotes : [],
    misconceptions: Array.isArray(misconceptions) ? misconceptions : [],
    evidenceQuestions: Array.isArray(evidenceQuestions) ? evidenceQuestions : [],
    pronunciationTips: Array.isArray(pronunciationTips) ? pronunciationTips : [],
    letterRecognitionTips: Array.isArray(letterRecognitionTips) ? letterRecognitionTips : [],
    writingTips: Array.isArray(writingTips) ? writingTips : [],
    vocabularyGroups: Array.isArray(vocabularyGroups) ? vocabularyGroups : [],
    translationHints: Array.isArray(translationHints) ? translationHints : [],
    readingPractice: Array.isArray(readingPractice) ? readingPractice : [],
    listeningPractice: Array.isArray(listeningPractice) ? listeningPractice : [],
    speakingPractice: Array.isArray(speakingPractice) ? speakingPractice : [],
    writingPractice: Array.isArray(writingPractice) ? writingPractice : [],
    commonPronunciationMistakes: Array.isArray(commonPronunciationMistakes) ? commonPronunciationMistakes : [],
    dailyPractice: Array.isArray(dailyPractice) ? dailyPractice : [],
    adabApplications: Array.isArray(adabApplications) ? adabApplications : [],
    realLifeExamples: Array.isArray(realLifeExamples) ? realLifeExamples : [],
    ayahOrHadithReference: Array.isArray(ayahOrHadithReference) ? ayahOrHadithReference : [],
    reflectionQuestions: Array.isArray(reflectionQuestions) ? reflectionQuestions : [],
    goodDeedsIdeas: Array.isArray(goodDeedsIdeas) ? goodDeedsIdeas : [],
    relatedTopics: Array.isArray(relatedTopics) ? relatedTopics : [],
    difficulty: String(difficulty || 'easy'),
    curriculum: curriculum && typeof curriculum === 'object' ? { ...curriculum } : {},
    keywords: Array.isArray(keywords) ? keywords : [],
    questionPatterns: Array.isArray(questionPatterns) ? questionPatterns : [],
    wrongAnswerPatterns: Array.isArray(wrongAnswerPatterns) ? wrongAnswerPatterns : [],
    followUpQuestions: Array.isArray(followUpQuestions) ? followUpQuestions : [],
    encouragement: {
      correct: Array.isArray(encouragement.correct) ? encouragement.correct : [],
      retry: Array.isArray(encouragement.retry) ? encouragement.retry : [],
      excellent: Array.isArray(encouragement.excellent) ? encouragement.excellent : []
    }
  };
}

export function normalizeKnowledgePack(pack = {}) {
  return createKnowledgePack(pack);
}

export default {
  KNOWLEDGE_PACK_VERSION,
  createKnowledgePack,
  normalizeKnowledgePack
};
